
#district{
	polygon-fill:#00782A;
	line-color:#00782A;
}
#piccadilly{
	polygon-fill:#003688;
	line-color:#003688;
}
#overground{
	polygon-fill:#EE7C0E;
	line-color:#EE7C0E;
}
#metropolitan{
	polygon-fill:#9B0056;
	line-color:#9B0056;
}
#hammersmithandcity{
	polygon-fill:#F3A9BB;
	line-color:#F3A9BB;
}
#northern{
	polygon-fill:#000000;
	line-color:#000000;
}
#circle{
	polygon-fill:#FFD300;
	line-color:#FFD300;
}
#bakerloo{
	polygon-fill:#B36305;
	line-color:#B36305;
}
#jubilee{
	polygon-fill:#A0A5A9;
	line-color:#A0A5A9;
}
#central{
	polygon-fill:#E32017;
	line-color:#E32017;
}
#waterlooandcity{
	polygon-fill:#95CDBA;
	line-color:#95CDBA;
}
#victoria{
	polygon-fill:#0098D4;
	line-color:#0098D4;
}
#{
}
#dlr{
	polygon-fill:#00A4A7;
	line-color:#00A4A7;
}
#district_piccadilly{
	polygon-pattern-file:url('img/District_Piccadilly.png');
}
#district_hammersmithandcity{
	polygon-pattern-file:url('img/District_Hammersmith and City.png');
}
#circle_hammersmithandcity{
	polygon-pattern-file:url('img/Circle_Hammersmith and City.png');
}
#bakerloo_jubilee{
	polygon-pattern-file:url('img/Bakerloo_Jubilee.png');
}
#central_waterlooandcity{
	polygon-pattern-file:url('img/Central_Waterloo and City.png');
}
#circle_hammersmithandcity_metropolitan{
	polygon-pattern-file:url('img/Circle_Hammersmith and City_Metropolitan.png');
}
#circle_district{
	polygon-pattern-file:url('img/Circle_District.png');
}
#central_jubilee{
	polygon-pattern-file:url('img/Central_Jubilee.png');
}
#bakerloo_northern{
	polygon-pattern-file:url('img/Bakerloo_Northern.png');
}
#central_district{
	polygon-pattern-file:url('img/Central_District.png');
}
#metropolitan_piccadilly{
	polygon-pattern-file:url('img/Metropolitan_Piccadilly.png');
}
#circle_district_hammersmithandcity{
	polygon-pattern-file:url('img/Circle_District_Hammersmith and City.png');
}
#bakerloo_circle_district_northern{
	polygon-pattern-file:url('img/Bakerloo_Circle_District_Northern.png');
}
#jubilee_metropolitan{
	polygon-pattern-file:url('img/Jubilee_Metropolitan.png');
}
#piccadilly_victoria{
	polygon-pattern-file:url('img/Piccadilly_Victoria.png');
}
#circle_district_piccadilly{
	polygon-pattern-file:url('img/Circle_District_Piccadilly.png');
}
#jubilee_piccadilly_victoria{
	polygon-pattern-file:url('img/Jubilee_Piccadilly_Victoria.png');
}
#northern_overground_victoria{
	polygon-pattern-file:url('img/Northern_Overground_Victoria.png');
}
#central_piccadilly{
	polygon-pattern-file:url('img/Central_Piccadilly.png');
}
#circle_hammersmithandcity_metropolitan_northern_piccadilly_victoria{
	polygon-pattern-file:url('img/Circle_Hammersmith and City_Metropolitan_Northern_Piccadilly_Victoria.png');
}
#northern_piccadilly{
	polygon-pattern-file:url('img/Northern_Piccadilly.png');
}
#jubilee_northern{
	polygon-pattern-file:url('img/Jubilee_Northern.png');
}
#central_district_hammersmithandcity{
	polygon-pattern-file:url('img/Central_District_Hammersmith and City.png');
}
#circle_hammersmithandcity_metropolitan_northern_overground{
	polygon-pattern-file:url('img/Circle_Hammersmith and City_Metropolitan_Northern_Overground.png');
}
#central_circle_district{
	polygon-pattern-file:url('img/Central_Circle_District.png');
}
#bakerloo_central_victoria{
	polygon-pattern-file:url('img/Bakerloo_Central_Victoria.png');
}
#bakerloo_piccadilly{
	polygon-pattern-file:url('img/Bakerloo_Piccadilly.png');
}
#northern_victoria{
	polygon-pattern-file:url('img/Northern_Victoria.png');
}
#central_jubilee_overground{
	polygon-pattern-file:url('img/Central_Jubilee_Overground.png');
}
#jubilee_overground{
	polygon-pattern-file:url('img/Jubilee_Overground.png');
}
#central_northern{
	polygon-pattern-file:url('img/Central_Northern.png');
}
#circle_district_victoria{
	polygon-pattern-file:url('img/Circle_District_Victoria.png');
}
#bakerloo_northern_waterlooandcity{
	polygon-pattern-file:url('img/Bakerloo_Northern_Waterloo and City.png');
}
#district_hammersmithandcity_jubilee{
	polygon-pattern-file:url('img/District_Hammersmith and City_Jubilee.png');
}
#circle_district_jubilee{
	polygon-pattern-file:url('img/Circle_District_Jubilee.png');
}
#district_hammersmithandcity_overground{
	polygon-pattern-file:url('img/District_Hammersmith and City_Overground.png');
}